version: 0.0
os: linux
files:
  - source: settings.rb
    destination: /home/ec2-user/
  - source: scrap_live_events.rb
    destination: /home/ec2-user/
  - source: mailer_initializer.rb
    destination: /home/ec2-user/
  - source: Gemfile
    destination: /home/ec2-user/
  - source: Gemfile.lock
    destination: /home/ec2-user/
  - source: Rakefile
    destination: /home/ec2-user/
  - source: classes/
    destination: /home/ec2-user/classes/
  - source: bin/
    destination: /home/ec2-user/bin/
  - source: db/
    destination: /home/ec2-user/db/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/bundle_install
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
