# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Bundle and tests
        image: ruby:2.4.6
        caches:
          - bundler
        script:
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
          - bundle install
          - bundle exec rake db:setup
          - bundle exec rake db:test:prepare
          - bundle exec rspec
        services:
          - postgres
  branches:
    master:
      - step:
          name: Deploy
          image: python:3.7.3
          script:
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - zip -r /tmp/artifact.zip settings.rb scrap_live_events.rb load_files.rb mailer_initializer.rb appspec.yml Gemfile Gemfile.lock Rakefile bin/ classes/ scripts/ db/
            - python codedeploy_deploy.py
definitions:
  caches:
    bundler: ./vendor
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'