# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Bundle
        image: ruby:2.4.6
        caches:
          - bundler
        script:
          - bundle install
    - step:
        name: Deploy
        image: python:3.7.3
        script:
          - apt-get update
          - apt-get install -y zip
          - pip install boto3==1.3.0
          - zip -r /tmp/artifact.zip Gemfile Gemfile.lock bin/ classes/ settings.rb scrap_live_events.rb mailer_initializer.rb
          - python codedeploy_deploy.py
definitions:
  caches:
    bundler: ./vendor