default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

development:
  <<: *default
  database: web_scraper_development

test: &test
  <<: *default
  database: web_scraper_test

production:
  <<: *default
  database: web_scraper_production