#!/bin/bash

# pgrep -f "ruby scrap_live_events.rb"
# if [ $? -eq 0 ]
# then
#     echo "Found running server, stopping"
#     pkill -f "ruby scrap_live_events.rb"
# else
#     echo "Nothing to do"
# fi
exit 0